//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chucksoft.Client.PhotoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://chucksoft.com/", ConfigurationName="PhotoService.PhotoServiceSoap")]
    public interface PhotoServiceSoap {
        
        // CODEGEN: Generating message contract since element name token from namespace http://chucksoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://chucksoft.com/Upload", ReplyAction="*")]
        Chucksoft.Client.PhotoService.UploadResponse Upload(Chucksoft.Client.PhotoService.UploadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Upload", Namespace="http://chucksoft.com/", Order=0)]
        public Chucksoft.Client.PhotoService.UploadRequestBody Body;
        
        public UploadRequest() {
        }
        
        public UploadRequest(Chucksoft.Client.PhotoService.UploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chucksoft.com/")]
    public partial class UploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] image;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int galleryId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string imageFormat;
        
        public UploadRequestBody() {
        }
        
        public UploadRequestBody(string token, byte[] image, int galleryId, string imageFormat) {
            this.token = token;
            this.image = image;
            this.galleryId = galleryId;
            this.imageFormat = imageFormat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadResponse", Namespace="http://chucksoft.com/", Order=0)]
        public Chucksoft.Client.PhotoService.UploadResponseBody Body;
        
        public UploadResponse() {
        }
        
        public UploadResponse(Chucksoft.Client.PhotoService.UploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UploadResponseBody {
        
        public UploadResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PhotoServiceSoapChannel : Chucksoft.Client.PhotoService.PhotoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PhotoServiceSoapClient : System.ServiceModel.ClientBase<Chucksoft.Client.PhotoService.PhotoServiceSoap>, Chucksoft.Client.PhotoService.PhotoServiceSoap {
        
        public PhotoServiceSoapClient() {
        }
        
        public PhotoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhotoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhotoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chucksoft.Client.PhotoService.UploadResponse Chucksoft.Client.PhotoService.PhotoServiceSoap.Upload(Chucksoft.Client.PhotoService.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public void Upload(string token, byte[] image, int galleryId, string imageFormat) {
            Chucksoft.Client.PhotoService.UploadRequest inValue = new Chucksoft.Client.PhotoService.UploadRequest();
            inValue.Body = new Chucksoft.Client.PhotoService.UploadRequestBody();
            inValue.Body.token = token;
            inValue.Body.image = image;
            inValue.Body.galleryId = galleryId;
            inValue.Body.imageFormat = imageFormat;
            Chucksoft.Client.PhotoService.UploadResponse retVal = ((Chucksoft.Client.PhotoService.PhotoServiceSoap)(this)).Upload(inValue);
        }
    }
}
