//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chucksoft.Client.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://chucksoft.com/", ConfigurationName="UserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetTokenResult from namespace http://chucksoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://chucksoft.com/GetToken", ReplyAction="*")]
        Chucksoft.Client.UserService.GetTokenResponse GetToken(Chucksoft.Client.UserService.GetTokenRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://chucksoft.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://chucksoft.com/GetTokenByUsernameAndPassword", ReplyAction="*")]
        Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordResponse GetTokenByUsernameAndPassword(Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="http://chucksoft.com/", Order=0)]
        public Chucksoft.Client.UserService.GetTokenRequestBody Body;
        
        public GetTokenRequest() {
        }
        
        public GetTokenRequest(Chucksoft.Client.UserService.GetTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chucksoft.com/")]
    public partial class GetTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid serviceKey;
        
        public GetTokenRequestBody() {
        }
        
        public GetTokenRequestBody(System.Guid serviceKey) {
            this.serviceKey = serviceKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="http://chucksoft.com/", Order=0)]
        public Chucksoft.Client.UserService.GetTokenResponseBody Body;
        
        public GetTokenResponse() {
        }
        
        public GetTokenResponse(Chucksoft.Client.UserService.GetTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chucksoft.com/")]
    public partial class GetTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenResult;
        
        public GetTokenResponseBody() {
        }
        
        public GetTokenResponseBody(string GetTokenResult) {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenByUsernameAndPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenByUsernameAndPassword", Namespace="http://chucksoft.com/", Order=0)]
        public Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordRequestBody Body;
        
        public GetTokenByUsernameAndPasswordRequest() {
        }
        
        public GetTokenByUsernameAndPasswordRequest(Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chucksoft.com/")]
    public partial class GetTokenByUsernameAndPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetTokenByUsernameAndPasswordRequestBody() {
        }
        
        public GetTokenByUsernameAndPasswordRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenByUsernameAndPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenByUsernameAndPasswordResponse", Namespace="http://chucksoft.com/", Order=0)]
        public Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordResponseBody Body;
        
        public GetTokenByUsernameAndPasswordResponse() {
        }
        
        public GetTokenByUsernameAndPasswordResponse(Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://chucksoft.com/")]
    public partial class GetTokenByUsernameAndPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTokenByUsernameAndPasswordResult;
        
        public GetTokenByUsernameAndPasswordResponseBody() {
        }
        
        public GetTokenByUsernameAndPasswordResponseBody(string GetTokenByUsernameAndPasswordResult) {
            this.GetTokenByUsernameAndPasswordResult = GetTokenByUsernameAndPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface UserServiceSoapChannel : Chucksoft.Client.UserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<Chucksoft.Client.UserService.UserServiceSoap>, Chucksoft.Client.UserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chucksoft.Client.UserService.GetTokenResponse Chucksoft.Client.UserService.UserServiceSoap.GetToken(Chucksoft.Client.UserService.GetTokenRequest request) {
            return base.Channel.GetToken(request);
        }
        
        public string GetToken(System.Guid serviceKey) {
            Chucksoft.Client.UserService.GetTokenRequest inValue = new Chucksoft.Client.UserService.GetTokenRequest();
            inValue.Body = new Chucksoft.Client.UserService.GetTokenRequestBody();
            inValue.Body.serviceKey = serviceKey;
            Chucksoft.Client.UserService.GetTokenResponse retVal = ((Chucksoft.Client.UserService.UserServiceSoap)(this)).GetToken(inValue);
            return retVal.Body.GetTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordResponse Chucksoft.Client.UserService.UserServiceSoap.GetTokenByUsernameAndPassword(Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordRequest request) {
            return base.Channel.GetTokenByUsernameAndPassword(request);
        }
        
        public string GetTokenByUsernameAndPassword(string username, string password) {
            Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordRequest inValue = new Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordRequest();
            inValue.Body = new Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Chucksoft.Client.UserService.GetTokenByUsernameAndPasswordResponse retVal = ((Chucksoft.Client.UserService.UserServiceSoap)(this)).GetTokenByUsernameAndPassword(inValue);
            return retVal.Body.GetTokenByUsernameAndPasswordResult;
        }
    }
}
